### ISSUE TITLE
New Update for 3cx v16

### ISSUE THREAD

**Issue by abbasfarahani1979** [disgustipated/MicrosoftDynamicsCRM#3]
**Hi**

Do you have any plan for new release of your plugin (MicrosoftDynamicsCRM) compatible with 3CX v16?

We are using 3CX (v16) and Dynamics365 (V8.2) on-premise, but the CallState Method return unanswered value when we pickup the phone. also we get 0 minute as ActualDurationMinutes.
from above now we have some question:

1-why we get unanswered value even we answered our phone?
2-why we get 0 minute in duration field on CRM after end call?
3-we need link of Saved voice file from 3cx call in our phone call entity, can we have it?

**your suggestion would be appreciated.**

**Comment by disgustipated** [comment]
No, sorry, I havent looked at the code in quite a while. Last I heard they (3cx) were going to be changing how these plugins worked. To be clear I only made a couple modifications to the built in 3CX plugin to add check boxes to choose to open an activity and a couple other minor changes. If 3cx is still using the same plugin architecture you might be able to pull their latest version down and do a diff to the features you might be using from my code.

Your other questions I'm not sure i could help with. I do know the third one would require quite a bit of development to start from scratch. for accessing recorded calls for our own 3cx implementation we use another plugin called voiptools
https://www.voiptools.com/product/3cx-recording-manager-by-voiptools/
Hope that helps!
